/*
gps: 'GPS', 
            usb: 'USB', 
            'radio cd': 'Rádio CD', 
            bluetooth: 'Bluetooth', 
            'jante sespeciais': 'Jantes especiais',
            'camera traseira': 'Câmara traseira',
            'cruise control': 'Cruise control',
            jantes: 'Jantes',
            'farois xenon': 'Faróis xenon',
            'farois led': 'Faróis LED',
            'farois nevoeiro': 'Faróis de nevoeiro',
            'volante multifuncoes': 'Volante multifunções',
            'volante pele': 'Volante em pele',
            ac: 'Ar condicionado',
            'climatizacao auto': 'Climatização automática',
            'climatizacao bi-zona': 'Climatização bi-zona',
            'sensores luz': 'Sensores de luz',
            'sensores chuva': 'Sensores de chuva',
            'sensores frontais': 'Sensores frontais',
            'sensores traseiros': 'Sensores traseiros',
            abs: 'ABS',
            esp: 'ESP',
            'direcao assistida': 'Direção assistida',
            'fecho central': 'Fecho central',




            extras: ["gps","usb","radio cd","bluetooth","jante sespeciais", "camera traseira","cruise control","jantes","farois xenon","farois led", "farois nevoeiro", "volante multifuncoes", "volante pele","ac", "climatizacao auto","climatizacao bi-zona","sensores de luz","sensores chuva","sensores frontais","sensores traseiros","abs","esp", "direcao assistida", "fecho central"],
*/
const stockGuimacar = [
    {
        id: 1,
        marca: "Renault Clio",
        destaque: true,
        modelo: "1.5 Dci 75 CV 2017",
        preco: "10.250 €",
        mes: "12/2017",
        kms: "117.000",
        combustivel: "Gasóleo",
        cilindrada: "1500",
        potencia: "75",
        extras: [],
        fotos: [
            "img/carro1/1.jpg",
            "img/carro1/2.jpg",
            "img/carro1/3.jpg",
            "img/carro1/4.jpg",
            "img/carro1/5.jpg",
            "img/carro1/6.jpg",
            "img/carro1/7.jpg",
            "img/carro1/8.jpg",
            "img/carro1/9.jpg" 
        ]
    },
    {
        id: 2,
        marca: "Polo Go",
        destaque: false,
        modelo: "1.4 TDI",
        preco: "5.750 €",
        mes: "09/2006",
        kms: "203.000",
        combustivel: "Gasóleo",
        cilindrada: "1400",
        potencia: "",
        extras:[],
        fotos: [
            "img/carro11/1.jpg",
            "img/carro11/2.jpg",
            "img/carro11/3.jpg",
            "img/carro11/4.jpg",
            "img/carro11/5.jpg",
            "img/carro11/6.jpg",
            "img/carro11/7.jpg",
            "img/carro11/8.jpg",
            "img/carro11/9.jpg",
            "img/carro11/10.jpg",
            "img/carro11/11.jpg"
        ]
    },

    {
        id: 3,
        marca: "Citroen C3",
        destaque: true,
        modelo: "1.2 2019",
        preco: "9.750 €",
        mes: "10/2019",
        kms: "104.300",
        combustivel: "Gasolina",
        cilindrada: "1200",
        potencia: "75",
        extras: [],
        fotos: [
            "img/carro3/1.jpg",
            "img/carro3/2.jpg",
            "img/carro3/3.jpg",
            "img/carro3/4.jpg",
            "img/carro3/5.jpg",
            "img/carro3/6.jpg",
            "img/carro3/7.jpg",
            "img/carro3/8.jpg",
            "img/carro3/9.jpg",
            "img/carro3/10.jpg",
            "img/carro3/11.jpg",
            "img/carro3/12.jpg",
            "img/carro3/13.jpg",
            "img/carro3/14.jpg"

        ]
    },
    {
        id: 4,
        marca: "Peugeot Partner 1.6 Hdi",
        destaque: true,
        ivaDedutivel: true,
        modelo: "AC 3L 2019 ",
        preco: "12.500 €",
        mes: "07/2019",
        kms: "147.200",
        combustivel: "Gasóleo",
        cilindrada: "1600",
        potencia: "75",
        extras: ["usb","radio cd","bluetooth","cruise control","direcao assistida", "fecho central", "ac","sensores traseiros","abs","esp"],
        fotos: [
            "img/carro4/1.jpg",
            "img/carro4/2.jpg",
            "img/carro4/3.jpg",
            "img/carro4/4.jpg",
            "img/carro4/5.jpg",
            "img/carro4/6.jpg",
            "img/carro4/7.jpg",
            "img/carro4/8.jpg",
            "img/carro4/9.jpg",
            "img/carro4/10.jpg",
            "img/carro4/11.jpg",
            "img/carro4/12.jpg",
            "img/carro4/13.jpg",
            "img/carro4/14.jpg"
        ]
    },
    {
        id: 5,
        marca: "Peugeot 308 Allure Hdi",
        destaque: true,
        modelo: "SW 2018",
        preco: "13.750 €",
        mes: "05/2018",
        kms: "135.000",
        combustivel: "Gasóleo",
        cilindrada: "1500",
        potencia: "130",
        extras: [],
        fotos: [
            "img/carro5/1.jpg",
            "img/carro5/2.jpg",
            "img/carro5/3.jpg",
            "img/carro5/4.jpg",
            "img/carro5/5.jpg",
            "img/carro5/6.jpg",
            "img/carro5/7.jpg",
            "img/carro5/8.jpg",
            "img/carro5/9.jpg",
            "img/carro5/10.jpg",
            "img/carro5/11.jpg",
            "img/carro5/12.jpg",
            "img/carro5/13.jpg",
            "img/carro5/14.jpg",
            "img/carro5/15.jpg",
            "img/carro5/16.jpg",
            "img/carro5/17.jpg",
            "img/carro5/18.jpg"
        ]
    },
    {
        id: 6,
        marca: "Peugeot 308 Hdi",
        destaque: true,
        modelo: "1.5 Hdi 2019",
        preco: "13.750 €",
        mes: "07/2019",
        kms: "146.100",
        combustivel: "Gasóleo",
        cilindrada: "1500",
        potencia: "100",
        extras:["gps","usb","bluetooth","jantes","farois led", "farois nevoeiro","cruise control","direcao assistida", "volante pele", "volante multifuncoes", "fecho central", "ac", "climatizacao auto","climatizacao bi-zona","sensores de luz","sensores chuva","sensores traseiros","abs","esp"],
        fotos: [
            "img/carro6/1.jpg",
            "img/carro6/2.jpg",
            "img/carro6/3.jpg",
            "img/carro6/4.jpg",
            "img/carro6/5.jpg",
            "img/carro6/6.jpg",
            "img/carro6/7.jpg",
            "img/carro6/8.jpg",
            "img/carro6/9.jpg",
            "img/carro6/10.jpg",
            "img/carro6/11.jpg",
            "img/carro6/12.jpg",
            "img/carro6/13.jpg",
            "img/carro6/14.jpg"
        ]
    },
    {
        id: 7,
        marca: "Renault Captur",
        destaque: true,
        modelo: "1.5 DCI 2016",
        preco: "10.250 €",
        mes: "10/2016",
        kms: "163.000",
        combustivel: "Gasóleo",
        cilindrada: "1500",
        potencia: "90",
        extras:[],
        fotos: [
            "img/carro7/1.jpg",
            "img/carro7/2.jpg",
            "img/carro7/3.jpg",
            "img/carro7/4.jpg",
            "img/carro7/5.jpg",
            "img/carro7/6.jpg",
            "img/carro7/7.jpg",
            "img/carro7/8.jpg",
            "img/carro7/9.jpg",
            "img/carro7/10.jpg"
        ]
    }
    ,
    {
        id: 8,
        marca: "Opel Corsa D",
        destaque: false,
        modelo: "1.3 CDTi ecoFLEX ",
        preco: "5.750 €",
        mes: "03/2008",
        kms: "107.000",
        combustivel: "Gasóleo",
        cilindrada: "1300",
        potencia: "75",
        extras:[],
        fotos: [
            "img/carro8/1.jpg",
            "img/carro8/2.jpg",
            "img/carro8/3.jpg",
            "img/carro8/4.jpg",
            "img/carro8/5.jpg",
            "img/carro8/6.jpg",
            "img/carro8/7.jpg",
            "img/carro8/8.jpg",
            "img/carro8/9.jpg",
            "img/carro8/10.jpg",
            "img/carro8/11.jpg"
        ]
    },
    /*
    {
        id: 8,
        marca: "Opel Corsa d",
        destaque: false,
        modelo: "1.2 CDTI ECO FLEX ",
        preco: "Sob Consulta",
        mes: "03/2008",
        kms: "107000",
        combustivel: "Gasolina",
        cilindrada: "1200",
        potencia: "75",
        extras:[],
        fotos: [
            "img/carro8/1.jpg",
            "img/carro8/2.jpg",
            "img/carro8/3.jpg",
            "img/carro8/4.jpg",
            "img/carro8/5.jpg",
            "img/carro8/6.jpg",
            "img/carro8/7.jpg",
            "img/carro8/8.jpg",
            "img/carro8/9.jpg",
            "img/carro8/10.jpg",
            "img/carro8/11.jpg"
        ]
    },
    */

   {
        id: 9,
        marca: "Citroen C4 Van",
        destaque: false,
        modelo: "1.6 Hdi 2010",
        preco: "4.500 €",
        mes: "02/2010",
        kms: "189.000",
        combustivel: "Gasóleo",
        cilindrada: "1600",
        potencia: "92",
        extras: ["ac"], 
        fotos: [
            "img/carro9/1.JPG",
            "img/carro9/2.JPG",
            "img/carro9/3.JPG",
            "img/carro9/4.JPG",
            "img/carro9/5.JPG",
            "img/carro9/6.JPG",
            "img/carro9/7.JPG",
            "img/carro9/8.JPG",
            "img/carro9/9.JPG",
            "img/carro9/10.JPG"
        ]
    },
   {
        id: 11,
        marca: "Citroen C4 2011",
        destaque: false,
        modelo: "1.6 Hdi 2011",
        preco: "8.250 €",
        mes: "03/2011",
        kms: "190.000",
        combustivel: "Gasóleo",
        cilindrada: "1600",
        potencia: "90",
        extras: [], 
        fotos: [
            "img/carro10/1.jpg",
            "img/carro10/2.jpg",
            "img/carro10/3.jpg",
            "img/carro10/4.jpg",
            "img/carro10/5.jpg",
            "img/carro10/6.jpg",
            "img/carro10/7.jpg",
            "img/carro10/8.jpg",
            "img/carro10/9.jpg",
            "img/carro10/10.jpg",
            "img/carro10/11.jpg",
            "img/carro10/12.jpg"
        ]
    },

    {
        id: 12,
        marca: "Opel Corsa",
        destaque: false,
        brevemente: true,
        modelo: "1.2 Turbo",
        preco: "Sob Consulta",
        mes: "06/2021",
        kms: "83.000",
        combustivel: "Gasolina",
        cilindrada: "1200",
        potencia: "",
        extras:[],
        fotos: [
            "img/carro12/1.jpg",
            "img/carro12/2.jpg",
            "img/carro12/3.jpg"
 
        ]
    }
    ,
    {
        id: 13,
        marca: "Renault Clio",
        destaque: false,
        modelo: "1.5 Dci 75 CV 2018",
        preco: "10.250 €",
        mes: "07/2018",
        kms: "149.350",
        combustivel: "Gasóleo",
        cilindrada: "1500",
        potencia: "75",
        extras: [],
        fotos: [
            "img/carro13/1.jpg",
            "img/carro13/2.jpg",
            "img/carro13/3.jpg",
            "img/carro13/4.jpg",
            "img/carro13/5.jpg",
            "img/carro13/6.jpg",
            "img/carro13/7.jpg",
            "img/carro13/8.jpg"
        ]
    },
    {
        id: 14,
        marca: "Peugeot 208",
        destaque: false,
        modelo: "Signature 1.2 PureTech 82 CV 2019",
        preco: "9.750 €",
        mes: "03/2019",
        kms: "99.600",
        combustivel: "Gasolina",
        cilindrada: "1200",
        potencia: "82",
        extras: [],
        fotos: [
            "img/carro14/1.jpg",
            "img/carro14/2.jpg",
            "img/carro14/3.jpg",
            "img/carro14/4.jpg",
            "img/carro14/5.jpg",
            "img/carro14/6.jpg",
            "img/carro14/7.jpg",
            "img/carro14/8.jpg"
        ]
    },
    {
        id: 15,
        marca: "Renault Kadjar",
        destaque: false,
        modelo: "dCi 130 CV Energy Intens 2016",
        preco: "13.500 €",
        mes: "05/2016",
        kms: "153.500",
        combustivel: "Gasolina",
        cilindrada: "1600",
        potencia: "130",
        extras: [],
        fotos: [
            "img/carro15/1.jpg",
            "img/carro15/2.jpg",
            "img/carro15/3.jpg",
            "img/carro15/4.jpg",
            "img/carro15/5.jpg",
            "img/carro15/6.jpg",
            "img/carro15/7.jpg",
            "img/carro15/8.jpg",
            "img/carro15/9.jpg",
            "img/carro15/10.jpg"
        ]
    },
    {
        id: 16,
        marca: "Fiat Tipo",
        destaque: false,
        modelo: "1.3 CDTI 95 CV 2019",
        preco: "7.750 €",
        mes: "12/2019",
        kms: "186.350",
        combustivel: "Gasóleo",
        cilindrada: "1300",
        potencia: "95",
        extras: [],
        fotos: [
            "img/carro16/1.jpg",
            "img/carro16/2.jpg",
            "img/carro16/3.jpg",
            "img/carro16/4.jpg",
            "img/carro16/5.jpg",
            "img/carro16/6.jpg",
            "img/carro16/7.jpg",
            "img/carro16/8.jpg",
            "img/carro16/9.jpg",
            "img/carro16/10.jpg"
        ]
    }
];
