/*
gps: 'GPS',
            usb: 'USB',
            'radio cd': 'Rádio CD',
            bluetooth: 'Bluetooth',
            'jante sespeciais': 'Jantes especiais',
            'camera traseira': 'Câmara traseira',
            'cruise control': 'Cruise control',
            jantes: 'Jantes',
            'farois xenon': 'Faróis xenon',
            'farois led': 'Faróis LED',
            'farois nevoeiro': 'Faróis de nevoeiro',
            'volante multifuncoes': 'Volante multifunções',
            'volante pele': 'Volante em pele',
            ac: 'Ar condicionado',
            'climatizacao auto': 'Climatização automática',
            'climatizacao bi-zona': 'Climatização bi-zona',
            'sensores luz': 'Sensores de luz',
            'sensores chuva': 'Sensores de chuva',
            'sensores frontais': 'Sensores frontais',
            'sensores traseiros': 'Sensores traseiros',
            abs: 'ABS',
            esp: 'ESP',
            'direcao assistida': 'Direção assistida',
            'fecho central': 'Fecho central',
*/
const stockGuimacar = [
    {
        id: 1,
        marca: "Renault Megane",
        destaque: true,
        modelo: "1.5 Dci 110 CV 2018",
        preco: "14.250 €",
        mes: "05/2018",
        kms: "123.700",
        combustivel: "Gasóleo",
        cilindrada: "1500",
        potencia: "110",
        registos: "N/C",
        extras: ["gps","usb","bluetooth","farois led", "farois nevoeiro","cruise control","direcao assistida", "volante pele", "volante multifuncoes", "fecho central", "ac", "climatizacao auto","climatizacao bi-zona","sensores de luz","sensores chuva","sensores frontais","sensores traseiros","abs","esp"],
        fotos: [
            "img/carro1/1.jpg",
            "img/carro1/2.jpg",
            "img/carro1/3.jpg",
            "img/carro1/4.jpg",
            "img/carro1/5.jpg",
            "img/carro1/6.jpg",
            "img/carro1/7.jpg",
            "img/carro1/8.jpg",
            "img/carro1/9.jpg",
            "img/carro1/10.jpg",
            "img/carro1/11.jpg"
        ]
    },
    {
        id: 2,
        marca: "Citroen Berlingo Longa",
        destaque: true,
        modelo: "1.6 Hdi 3L 2018",
        preco: "10.250 €",
        mes: "06/2018",
        kms: "142.100",
        combustivel: "Gasóleo",
        cilindrada: "1600",
        potencia: "100",
        registos: "N/C",
        extras: ["gps","bluetooth","cruise control","direcao assistida", "volante multifuncoes", "fecho central","sensores traseiros","abs","esp"],
        fotos: [
            "img/carro2/1.jpg",
            "img/carro2/2.jpg",
            "img/carro2/3.jpg",
            "img/carro2/4.jpg",
            "img/carro2/5.jpg",
            "img/carro2/6.jpg",
            "img/carro2/7.jpg",
            "img/carro2/8.jpg",
            "img/carro2/9.jpg",
            "img/carro2/10.jpg",
            "img/carro2/11.jpg",
            "img/carro2/12.jpg",
            "img/carro2/13.jpg",
            "img/carro2/14.jpg",
            "img/carro2/15.jpg",
            "img/carro2/16.jpg",
            "img/carro2/17.jpg"
        ]
    },
    {
        id: 3,
        marca: "Citroen C3",
        destaque: true,
        modelo: "1.2 2019",
        preco: "9.750 €",
        mes: "10/2019",
        kms: "88.000",
        combustivel: "Gasolina",
        cilindrada: "1200",
        potencia: "",
        registos: "N/C",
        extras: [],
        fotos: [
            "img/carro3/1.jpg",
            "img/carro3/2.jpg",
            "img/carro3/3.jpg",
            "img/carro3/4.jpg",
            "img/carro3/5.jpg",
            "img/carro3/6.jpg",
            "img/carro3/7.jpg",
            "img/carro3/8.jpg",
            "img/carro3/9.jpg",
            "img/carro3/10.jpg",
            "img/carro3/11.jpg",
            "img/carro3/12.jpg",
            "img/carro3/13.jpg",
            "img/carro3/14.jpg",
            "img/carro3/15.jpg",
            "img/carro3/16.jpg",
            "img/carro3/17.jpg"

        ]
    },
    {
        id: 4,
        marca: "Peugeot Partner",
        destaque: true,
        modelo: "1.6 Hdi AC 3L 2019",
        preco: "12.999 €",
        mes: "07/2019",
        kms: "147.200",
        combustivel: "Gasóleo",
        cilindrada: "1600",
        potencia: "75",
        registos: "N/C",
        extras: ["usb","radio cd","bluetooth","cruise control","direcao assistida", "fecho central", "ac","sensores traseiros","abs","esp"],
        fotos: [
            "img/carro4/1.jpg",
            "img/carro4/2.jpg",
            "img/carro4/3.jpg",
            "img/carro4/4.jpg",
            "img/carro4/5.jpg",
            "img/carro4/6.jpg",
            "img/carro4/7.jpg",
            "img/carro4/8.jpg",
            "img/carro4/9.jpg",
            "img/carro4/10.jpg",
            "img/carro4/11.jpg",
            "img/carro4/12.jpg",
            "img/carro4/13.jpg",
            "img/carro4/14.jpg"
        ]
    },
    {
        id: 5,
        marca: "Peugeot",
        destaque: true,
        modelo: "308 SW 2019",
        preco: "13.750 €",
        mes: "05/2018",
        kms: "135.000",
        combustivel: "Gasóleo",
        cilindrada: "1500",
        potencia: "130",
        registos: "N/C",
        extras: [],
        fotos: [
            "img/carro5/1.jpg",
            "img/carro5/2.jpg",
            "img/carro5/3.jpg",
            "img/carro5/4.jpg",
            "img/carro5/5.jpg",
            "img/carro5/6.jpg",
            "img/carro5/7.jpg",
            "img/carro5/8.jpg",
            "img/carro5/9.jpg",
            "img/carro5/10.jpg",
            "img/carro5/11.jpg",
            "img/carro5/12.jpg",
            "img/carro5/13.jpg",
            "img/carro5/14.jpg",
            "img/carro5/15.jpg",
            "img/carro5/16.jpg",
            "img/carro5/17.jpg",
            "img/carro5/18.jpg"
        ]
    },
    {
        id: 6,
        marca: "Peugeot",
        destaque: true,
        modelo: "308 Hdi 2019",
        preco: "A DEFINIR",
        mes: "07/2019",
        kms: "146.100",
        combustivel: "Gasóleo",
        cilindrada: "1500",
        potencia: "100",
        registos: "N/C",
        extras:["gps","usb","bluetooth","jantes","farois led", "farois nevoeiro","cruise control","direcao assistida", "volante pele", "volante multifuncoes", "fecho central", "ac", "climatizacao auto","climatizacao bi-zona","sensores de luz","sensores chuva","sensores traseiros","abs","esp"],
        fotos: [
            "img/carro6/1.jpg",
            "img/carro6/2.jpg",
            "img/carro6/3.jpg",
            "img/carro6/4.jpg",
            "img/carro6/5.jpg",
            "img/carro6/6.jpg",
            "img/carro6/7.jpg",
            "img/carro6/8.jpg",
            "img/carro6/9.jpg",
            "img/carro6/10.jpg",
            "img/carro6/11.jpg",
            "img/carro6/12.jpg",
            "img/carro6/13.jpg",
            "img/carro6/14.jpg"
        ]
    }
];
