/*
gps: 'GPS', 
            usb: 'USB', 
            'radio cd': 'Rádio CD', 
            bluetooth: 'Bluetooth', 
            'jante sespeciais': 'Jantes especiais',
            'camera traseira': 'Câmara traseira',
            'cruise control': 'Cruise control',
            jantes: 'Jantes',
            'farois xenon': 'Faróis xenon',
            'farois led': 'Faróis LED',
            'farois nevoeiro': 'Faróis de nevoeiro',
            'volante multifuncoes': 'Volante multifunções',
            'volante pele': 'Volante em pele',
            ac: 'Ar condicionado',
            'climatizacao auto': 'Climatização automática',
            'climatizacao bi-zona': 'Climatização bi-zona',
            'sensores luz': 'Sensores de luz',
            'sensores chuva': 'Sensores de chuva',
            'sensores frontais': 'Sensores frontais',
            'sensores traseiros': 'Sensores traseiros',
            abs: 'ABS',
            esp: 'ESP',
            'direcao assistida': 'Direção assistida',
            'fecho central': 'Fecho central',




            extras: ["gps","usb","radio cd","bluetooth","jante sespeciais", "camera traseira","cruise control","jantes","farois xenon","farois led", "farois nevoeiro", "volante multifuncoes", "volante pele","ac", "climatizacao auto","climatizacao bi-zona","sensores de luz","sensores chuva","sensores frontais","sensores traseiros","abs","esp", "direcao assistida", "fecho central"],
*/
const stockGuimacar = [
    {
        id: 1,
        marca: "Renault Clio",
        destaque: true,
        modelo: "1.5 Dci 75 CV 2017",
        preco: "10.250 €",
        mes: "12/2017",
        kms: "117.000",
        combustivel: "Gasóleo",
        cilindrada: "1500",
        potencia: "75",
        extras: [],
        fotos: [
            "img/RenaultClio17/1.jpg",
            "img/RenaultClio17/2.jpg",
            "img/RenaultClio17/3.jpg",
            "img/RenaultClio17/4.jpg",
            "img/RenaultClio17/5.jpg",
            "img/RenaultClio17/6.jpg",
            "img/RenaultClio17/7.jpg",
            "img/RenaultClio17/8.jpg",
            "img/RenaultClio17/9.jpg" 
        ]
    },
    {
        id: 2,
        marca: "Polo Go",
        destaque: false,
        modelo: "1.4 TDI ",
        preco: "5.750 €",
        mes: "09/2006",
        kms: "203.000",
        combustivel: "Gasóleo",
        cilindrada: "1400",
        potencia: "",
        extras:[],
        fotos: [
            "img/PoloGo/1.jpg",
            "img/PoloGo/2.jpg",
            "img/PoloGo/3.jpg",
            "img/PoloGo/4.jpg",
            "img/PoloGo/5.jpg",
            "img/PoloGo/6.jpg",
            "img/PoloGo/7.jpg",
            "img/PoloGo/8.jpg",
            "img/PoloGo/9.jpg",
            "img/PoloGo/10.jpg",
            "img/PoloGo/11.jpg"
        ]
    },

    {
        id: 3,
        marca: "Citroën C3",
        destaque: true,
        modelo: "1.2 2019",
        preco: "9.750 €",
        mes: "10/2019",
        kms: "104.300",
        combustivel: "Gasolina",
        cilindrada: "1200",
        potencia: "75",
        extras: [],
        fotos: [
            "img/CitroenC3/1.jpg",
            "img/CitroenC3/2.jpg",
            "img/CitroenC3/3.jpg",
            "img/CitroenC3/4.jpg",
            "img/CitroenC3/5.jpg",
            "img/CitroenC3/6.jpg",
            "img/CitroenC3/7.jpg",
            "img/CitroenC3/8.jpg",
            "img/CitroenC3/9.jpg",
            "img/CitroenC3/10.jpg",
            "img/CitroenC3/11.jpg",
            "img/CitroenC3/12.jpg",
            "img/CitroenC3/13.jpg",
            "img/CitroenC3/14.jpg"

        ]
    },
    {
        id: 4,
        marca: "Peugeot Partner 1.6 Hdi",
        destaque: true,
        ivaDedutivel: true,
        modelo: "AC 3L 2019 ",
        preco: "12.500 €",
        mes: "07/2019",
        kms: "147.200",
        combustivel: "Gasóleo",
        cilindrada: "1600",
        potencia: "75",
        extras: ["usb","radio cd","bluetooth","cruise control","direcao assistida", "fecho central", "ac","sensores traseiros","abs","esp"],
        fotos: [
            "img/Partner2019Branca/1.jpg",
            "img/Partner2019Branca/2.jpg",
            "img/Partner2019Branca/3.jpg",
            "img/Partner2019Branca/4.jpg",
            "img/Partner2019Branca/5.jpg",
            "img/Partner2019Branca/6.jpg",
            "img/Partner2019Branca/7.jpg",
            "img/Partner2019Branca/8.jpg",
            "img/Partner2019Branca/9.jpg",
            "img/Partner2019Branca/10.jpg",
            "img/Partner2019Branca/11.jpg",
            "img/Partner2019Branca/12.jpg",
            "img/Partner2019Branca/13.jpg",
            "img/Partner2019Branca/14.jpg"
        ]
    },
    {
        id: 5,
        marca: "Citroën Berlingo",
        destaque: false,
        ivaDedutivel: true,
        modelo: "1.6 HDI 75 CV 2018",
        preco: "9.500 €",
        mes: "03/2018",
        kms: "156.150",
        combustivel: "Gasóleo",
        cilindrada: "1600",
        potencia: "75",
        extras: [],
        fotos: [
            "img/Berlingo/1.jpg",
            "img/Berlingo/2.jpg",
            "img/Berlingo/3.jpg",
            "img/Berlingo/4.jpg",
            "img/Berlingo/5.jpg",
            "img/Berlingo/6.jpg",
            "img/Berlingo/7.jpg"
        ]
    },
    {
        id: 6,
        marca: "Peugeot 308 Allure Hdi",
        destaque: true,
        modelo: "SW 2018",
        preco: "13.750 €",
        mes: "05/2018",
        kms: "135.000",
        combustivel: "Gasóleo",
        cilindrada: "1500",
        potencia: "130",
        extras: [],
        fotos: [
            "img/PeugeotAllure/1.jpg",
            "img/PeugeotAllure/2.jpg",
            "img/PeugeotAllure/3.jpg",
            "img/PeugeotAllure/4.jpg",
            "img/PeugeotAllure/5.jpg",
            "img/PeugeotAllure/6.jpg",
            "img/PeugeotAllure/7.jpg",
            "img/PeugeotAllure/8.jpg",
            "img/PeugeotAllure/9.jpg",
            "img/PeugeotAllure/10.jpg",
            "img/PeugeotAllure/11.jpg",
            "img/PeugeotAllure/12.jpg",
            "img/PeugeotAllure/13.jpg",
            "img/PeugeotAllure/14.jpg",
            "img/PeugeotAllure/15.jpg",
            "img/PeugeotAllure/16.jpg",
            "img/PeugeotAllure/17.jpg",
            "img/PeugeotAllure/18.jpg"
        ]
    },
    {
        id: 7,
        marca: "Peugeot 308",
        destaque: true,
        modelo: "1.5 Hdi 2019",
        preco: "13.750 €",
        mes: "07/2019",
        kms: "146.100",
        combustivel: "Gasóleo",
        cilindrada: "1500",
        potencia: "100",
        extras:["gps","usb","bluetooth","jantes","farois led", "farois nevoeiro","cruise control","direcao assistida", "volante pele", "volante multifuncoes", "fecho central", "ac", "climatizacao auto","climatizacao bi-zona","sensores de luz","sensores chuva","sensores traseiros","abs","esp"],
        fotos: [
            "img/Peugeot308/1.jpg",
            "img/Peugeot308/2.jpg",
            "img/Peugeot308/3.jpg",
            "img/Peugeot308/4.jpg",
            "img/Peugeot308/5.jpg",
            "img/Peugeot308/6.jpg",
            "img/Peugeot308/7.jpg",
            "img/Peugeot308/8.jpg",
            "img/Peugeot308/9.jpg",
            "img/Peugeot308/10.jpg",
            "img/Peugeot308/11.jpg",
            "img/Peugeot308/12.jpg",
            "img/Peugeot308/13.jpg",
            "img/Peugeot308/14.jpg"
        ]
    },
    {
        id: 8,
        marca: "Renault Captur",
        destaque: true,
        modelo: "1.5 DCI 2016",
        preco: "10.250 €",
        mes: "10/2016",
        kms: "163.000",
        combustivel: "Gasóleo",
        cilindrada: "1500",
        potencia: "90",
        extras:[],
        fotos: [
            "img/RenaultCaptur/1.jpg",
            "img/RenaultCaptur/2.jpg",
            "img/RenaultCaptur/3.jpg",
            "img/RenaultCaptur/4.jpg",
            "img/RenaultCaptur/5.jpg",
            "img/RenaultCaptur/6.jpg",
            "img/RenaultCaptur/7.jpg",
            "img/RenaultCaptur/8.jpg",
            "img/RenaultCaptur/9.jpg",
            "img/RenaultCaptur/10.jpg"
        ]
    }
    ,
    {
        id: 9,
        marca: "Dacia Duster",
        destaque: false,
        modelo: "1.5 DCI 4x4",
        preco: "12.500 €",
        mes: "12/2017",
        kms: "181.100",
        combustivel: "Gasóleo",
        cilindrada: "1500",
        potencia: "110",
        extras:[],
        fotos: [
            "img/Duster/1.jpg",
            "img/Duster/2.jpg",
            "img/Duster/3.png",
            "img/Duster/4.jpg",
            "img/Duster/5.jpg",
            "img/Duster/6.jpg",
            "img/Duster/7.jpg"
        ]
    }
    ,
    {
        id: 10,
        marca: "Opel Corsa D",
        destaque: false,
        modelo: "1.3 CDTi ecoFLEX ",
        preco: "5.750 €",
        mes: "03/2008",
        kms: "107.000",
        combustivel: "Gasóleo",
        cilindrada: "1300",
        potencia: "75",
        extras:[],
        fotos: [
            "img/CorsaD/1.jpg",
            "img/CorsaD/2.jpg",
            "img/CorsaD/3.jpg",
            "img/CorsaD/4.jpg",
            "img/CorsaD/5.jpg",
            "img/CorsaD/6.jpg",
            "img/CorsaD/7.jpg",
            "img/CorsaD/8.jpg",
            "img/CorsaD/9.jpg",
            "img/CorsaD/10.jpg",
            "img/CorsaD/11.jpg"
        ]
    },
   {
        id: 11,
        marca: "Citroën C4 Van",
        destaque: false,
        modelo: "1.6 Hdi 2010",
        preco: "4.500 €",
        mes: "02/2010",
        kms: "189.000",
        combustivel: "Gasóleo",
        cilindrada: "1600",
        potencia: "92",
        extras: ["ac"], 
        fotos: [
            "img/CitroenC4Van/1.JPG",
            "img/CitroenC4Van/2.JPG",
            "img/CitroenC4Van/3.JPG",
            "img/CitroenC4Van/4.JPG",
            "img/CitroenC4Van/5.JPG",
            "img/CitroenC4Van/6.JPG",
            "img/CitroenC4Van/7.JPG",
            "img/CitroenC4Van/8.JPG",
            "img/CitroenC4Van/9.JPG",
            "img/CitroenC4Van/10.JPG"
        ]
    },
   {
        id: 12,
        marca: "Citroën C4",
        destaque: false,
        modelo: "1.6 Hdi 2011",
        preco: "8.250 €",
        mes: "03/2011",
        kms: "190.000",
        combustivel: "Gasóleo",
        cilindrada: "1600",
        potencia: "90",
        extras: [], 
        fotos: [
            "img/CitroenC4/1.jpg",
            "img/CitroenC4/2.jpg",
            "img/CitroenC4/3.jpg",
            "img/CitroenC4/4.jpg",
            "img/CitroenC4/5.jpg",
            "img/CitroenC4/6.jpg",
            "img/CitroenC4/7.jpg",
            "img/CitroenC4/8.jpg",
            "img/CitroenC4/9.jpg",
            "img/CitroenC4/10.jpg",
            "img/CitroenC4/11.jpg",
            "img/CitroenC4/12.jpg"
        ]
    },

    {
        id: 13,
        marca: "Opel Corsa",
        destaque: false,
        brevemente: true,
        modelo: "1.2 Turbo",
        preco: "Sob Consulta",
        mes: "06/2021",
        kms: "83.000",
        combustivel: "Gasolina",
        cilindrada: "1200",
        potencia: "",
        extras:[],
        fotos: [
            "img/Corsa2021/1.jpg",
            "img/Corsa2021/2.jpg",
            "img/Corsa2021/3.jpg"
 
        ]
    }
    ,
    {
        id: 14,
        marca: "Renault Clio",
        destaque: false,
        modelo: "1.5 Dci 75 CV 2018",
        preco: "10.250 €",
        mes: "07/2018",
        kms: "149.350",
        combustivel: "Gasóleo",
        cilindrada: "1500",
        potencia: "75",
        extras: [],
        fotos: [
            "img/RenaultClio18/1.jpg",
            "img/RenaultClio18/2.jpg",
            "img/RenaultClio18/3.jpg",
            "img/RenaultClio18/4.jpg",
            "img/RenaultClio18/5.jpg",
            "img/RenaultClio18/6.jpg",
            "img/RenaultClio18/7.jpg",
            "img/RenaultClio18/8.jpg"
        ]
    },
    {
        id: 15,
        marca: "Peugeot 208",
        destaque: false,
        modelo: "Signature 1.2 PureTech 82 CV 2019",
        preco: "9.750 €",
        mes: "03/2019",
        kms: "99.600",
        combustivel: "Gasolina",
        cilindrada: "1200",
        potencia: "82",
        extras: [],
        fotos: [
            "img/Peugeot208/1.jpg",
            "img/Peugeot208/2.jpg",
            "img/Peugeot208/3.jpg",
            "img/Peugeot208/4.jpg",
            "img/Peugeot208/5.jpg",
            "img/Peugeot208/6.jpg",
            "img/Peugeot208/7.jpg",
            "img/Peugeot208/8.jpg"
        ]
    },
    {
        id: 16,
        marca: "Renault Kadjar",
        destaque: false,
        modelo: "dCi 130 CV Energy Intens 2016",
        preco: "13.500 €",
        mes: "05/2016",
        kms: "153.500",
        combustivel: "Gasóleo",
        cilindrada: "1600",
        potencia: "130",
        extras: [],
        fotos: [
            "img/Kadjar/1.jpg",
            "img/Kadjar/2.jpg",
            "img/Kadjar/3.jpg",
            "img/Kadjar/4.jpg",
            "img/Kadjar/5.jpg",
            "img/Kadjar/6.jpg",
            "img/Kadjar/7.jpg",
            "img/Kadjar/8.jpg",
            "img/Kadjar/9.jpg",
            "img/Kadjar/10.jpg"
        ]
    },
    {
        id: 17,
        marca: "Fiat Tipo",
        destaque: false,
        modelo: "1.3 CDTI 95 CV 2019",
        preco: "7.750 €",
        mes: "12/2019",
        kms: "186.350",
        combustivel: "Gasóleo",
        cilindrada: "1300",
        potencia: "95",
        extras: [],
        fotos: [
            "img/FiatTipo/1.jpg",
            "img/FiatTipo/2.jpg",
            "img/FiatTipo/3.jpg",
            "img/FiatTipo/4.jpg",
            "img/FiatTipo/5.jpg",
            "img/FiatTipo/6.jpg",
            "img/FiatTipo/7.jpg",
            "img/FiatTipo/8.jpg",
            "img/FiatTipo/9.jpg",
            "img/FiatTipo/10.jpg"
        ]
    }
];
